project:
  name: plantomio
  hostname: plantomio.local
  wifi_ssid: plantomio_ap
  wifi_password: plantomio123
  mqtt:
    uri: mqtt://plantomio.local
    port: 1883
    username: plantomioX1
    client_id: plantomioX1
    password: plantomioX1Pass
    topic: v1/devices/me/telemetry
  victoria_metrics:
    port: 8428
  node_red:
    port: 1880
  dashboard:
    port: 5000

  node_red_username: "admin"
  # IMPORTANT: Generate the hash for your desired password using:
  #       node-red admin hash-pw YOUR_PASSWORD
  # and paste the output below., default is "admin"
  node_red_password_hash: "$2b$08$W99V1mAwhUg5M9.hX6kjY.qtLHyvk1YbiXIMQ8T.xafDsGHNEa1Na"